# Generated by Django 4.2.26 on 2026-02-17 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicaltrial",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="clinicaltrial",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinicaltrial",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinical_trials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
